[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
market_test = "Az88Wvk5gVMqFc7QQ94NqSa3sVCjnoQhjfNdqiti26fu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://niki-c1qc77-fast-devnet.helius-rpc.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
